--  login table
  CREATE TABLE "BASE_PARTY_ACCOUNT"
   (	"PARTY_ID" VARCHAR2(20 BYTE),
	"ACCOUNT_ID" VARCHAR2(50 BYTE),
	"ACCOUNT_PASSWORD" VARCHAR2(255 BYTE),
	"STATE" CHAR(1 BYTE),
	"EXP_DATE" DATE,
	"FAILED_LOGIN_COUNT" NUMBER(2,0),
	"UPD_TIMESTAMP" TIMESTAMP (6),
	"UPD_USERID" VARCHAR2(20 BYTE),
	"FAILED_LOGIN_ATTEMPTS" NUMBER,
	"ACCOUNT_KIND" VARCHAR2(50 BYTE),
	"LAST_LOGIN_DATE" TIMESTAMP (6),
	"CRT_TIMESTAMP" TIMESTAMP (6),
	"CRT_USERID" VARCHAR2(20 BYTE),
	"DATA_UPD_TIMESTAMP" TIMESTAMP (6),
	"DATA_UPD_USERID" VARCHAR2(20 BYTE),
	"EMAIL_LOGIN_STATE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."PARTY_ID" IS 'パーティーID';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."ACCOUNT_ID" IS 'アカウントID';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."ACCOUNT_PASSWORD" IS 'アカウントパスワード';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."STATE" IS '状態 0:有効 1:ロック';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."EXP_DATE" IS '有効期限';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."FAILED_LOGIN_COUNT" IS '失敗回数';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."UPD_TIMESTAMP" IS '更新日時';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."UPD_USERID" IS '更新者ID';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."FAILED_LOGIN_ATTEMPTS" IS '失敗許容回数';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."ACCOUNT_KIND" IS 'アカウント種別';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."LAST_LOGIN_DATE" IS '最終ログイン日時';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."CRT_TIMESTAMP" IS '作成日時';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."CRT_USERID" IS '作成者ID';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."DATA_UPD_TIMESTAMP" IS 'データ更新日時';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."DATA_UPD_USERID" IS 'データ更新ユーザID';
   COMMENT ON COLUMN "BASE_PARTY_ACCOUNT"."EMAIL_LOGIN_STATE" IS 'メールアドレスログイン可否（Ver.3.0.0より追加）';
   COMMENT ON TABLE "BASE_PARTY_ACCOUNT"  IS 'ログイン認証に必要なアカウント情報';
--logs table for login
    CREATE TABLE "BASE_PARTY_ATTRIBUTE"
      (	"PARTY_ID" VARCHAR2(20 BYTE),
   	"ATTRIBUTE_NAME" VARCHAR2(200 BYTE),
   	"ATTRIBUTE_SORT_NO" NUMBER,
   	"VALUE_1" VARCHAR2(100 BYTE),
   	"VALUE_2" VARCHAR2(100 BYTE),
   	"VALUE_3" VARCHAR2(100 BYTE),
   	"VALUE_4" VARCHAR2(100 BYTE),
   	"VALUE_5" VARCHAR2(100 BYTE),
   	"UPD_TIMESTAMP" TIMESTAMP (6),
   	"UPD_USERID" VARCHAR2(20 BYTE),
   	"CRT_TIMESTAMP" TIMESTAMP (6),
   	"CRT_USERID" VARCHAR2(20 BYTE)
      ) SEGMENT CREATION IMMEDIATE
     PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
     STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
     PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
     BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
     TABLESPACE "USERS" ;

      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."PARTY_ID" IS 'パーティーID';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."ATTRIBUTE_NAME" IS '属性名';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."ATTRIBUTE_SORT_NO" IS '属性ソートNo';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."VALUE_1" IS '値1';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."VALUE_2" IS '値2';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."VALUE_3" IS '値3';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."VALUE_4" IS '値4';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."VALUE_5" IS '値5';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."UPD_TIMESTAMP" IS '更新日時';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."UPD_USERID" IS '更新者ID';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."CRT_TIMESTAMP" IS '作成日時';
      COMMENT ON COLUMN "BASE_PARTY_ATTRIBUTE"."CRT_USERID" IS '作成者ID';
      COMMENT ON TABLE "BASE_PARTY_ATTRIBUTE"  IS '組織･ユーザ情報に紐づく属性（権限）情報';


--  DDL for Table M_GYOMU_IRAI   = used to store data related to business operations


    CREATE TABLE "M_GYOMU_IRAI"
   (	"CRT_TIMESTAMP" DATE,
	"CRT_USERID" VARCHAR2(20 BYTE),
	"UPD_TIMESTAMP" DATE,
	"UPD_USERID" VARCHAR2(20 BYTE),
	"SEQ_GYOMU_IRAI" NUMBER(28,0),
	"GYOMU_CD" VARCHAR2(10 BYTE),
	"LANG_FLG_JP" VARCHAR2(1 BYTE),
	"LANG_FLG_EN" VARCHAR2(1 BYTE),
	"GYOMU_NM_JP" VARCHAR2(300 BYTE),
	"GYOMU_NM_EN" VARCHAR2(300 BYTE),
	"DESCRIPTION_JP" VARCHAR2(3000 BYTE),
	"DESCRIPTION_EN" VARCHAR2(3000 BYTE),
	"SORT" NUMBER(28,0),
	"DEFINE_ID1" VARCHAR2(10 BYTE),
	"DEFINE_ID2" VARCHAR2(10 BYTE),
	"DEFINE_ID3" VARCHAR2(10 BYTE),
	"DEFINE_ID4" VARCHAR2(10 BYTE),
	"DEFINE_ID5" VARCHAR2(10 BYTE),
	"MAIL_FLG1" VARCHAR2(1 BYTE),
	"MAIL_FLG2" VARCHAR2(1 BYTE),
	"MAIL_FLG3" VARCHAR2(1 BYTE),
	"MAIL_FLG4" VARCHAR2(1 BYTE),
	"ATTACH_CLASS_NO_JP" NUMBER(28,0),
	"ATTACH_CLASS_NO_EN" NUMBER(28,0),
	"EDIT_AUTH_KBN" VARCHAR2(1 BYTE),
	"IRAISAKI_KBN" VARCHAR2(1 BYTE),
	"FILE_IMPORT_KBN" VARCHAR2(1 BYTE),
	"FORMAT_SEQ_NO_JP1" NUMBER(28,0),
	"FORMAT_SEQ_NO_JP2" NUMBER(28,0),
	"FORMAT_SEQ_NO_JP3" NUMBER(28,0),
	"FORMAT_SEQ_NO_JP4" NUMBER(28,0),
	"FORMAT_SEQ_NO_JP5" NUMBER(28,0),
	"FORMAT_SEQ_NO_EN1" NUMBER(28,0),
	"FORMAT_SEQ_NO_EN2" NUMBER(28,0),
	"FORMAT_SEQ_NO_EN3" NUMBER(28,0),
	"FORMAT_SEQ_NO_EN4" NUMBER(28,0),
	"FORMAT_SEQ_NO_EN5" NUMBER(28,0),
	"ATTACH_CLASS_NO_RIYOSHA" NUMBER(28,0),
	"DESCRIPTION_RIYOSHA" VARCHAR2(1200 BYTE),
	"REFERENCE_KBN" VARCHAR2(1 BYTE),
	"ACCESS_CTL_KBN" VARCHAR2(1 BYTE) DEFAULT '2',
	"MAIL_FLG5" VARCHAR2(1 BYTE),
	"GYOMU_DESC_OVERWRITE_KBN" VARCHAR2(1 BYTE),
	"SUBMIT_WITHDRAW_KBN" VARCHAR2(1 BYTE),
	"ATTACH_REQUIRED_KBN" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "M_GYOMU_IRAI"."CRT_TIMESTAMP" IS '作成日時';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."CRT_USERID" IS '作成者';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."UPD_TIMESTAMP" IS '更新日時';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."UPD_USERID" IS '更新者';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."SEQ_GYOMU_IRAI" IS 'シーケンス';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."GYOMU_CD" IS '業務CD';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."LANG_FLG_JP" IS '言語フラグ(日)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."LANG_FLG_EN" IS '言語フラグ(英)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."GYOMU_NM_JP" IS '業務名(日)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."GYOMU_NM_EN" IS '業務名(英)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DESCRIPTION_JP" IS '業務説明(日)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DESCRIPTION_EN" IS '業務説明(英)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."SORT" IS 'ソート';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DEFINE_ID1" IS '定義ID1';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DEFINE_ID2" IS '定義ID2';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DEFINE_ID3" IS '定義ID3';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DEFINE_ID4" IS '定義ID4';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."DEFINE_ID5" IS '定義ID5';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."MAIL_FLG1" IS 'メール連絡(マスタ変更)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."MAIL_FLG2" IS 'メール連絡(承認依頼)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."MAIL_FLG3" IS 'メール連絡(確認)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."MAIL_FLG4" IS 'メール連絡(差戻)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."ATTACH_CLASS_NO_JP" IS '添付集約No(日)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."ATTACH_CLASS_NO_EN" IS '添付集約No(英)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."IRAISAKI_KBN" IS '依頼先参照区分';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FILE_IMPORT_KBN" IS 'ファイル取込区分';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_JP1" IS '日本語フォーマット1';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_JP2" IS '日本語フォーマット2';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_JP3" IS '日本語フォーマット3';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_JP4" IS '日本語フォーマット4';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_JP5" IS '日本語フォーマット5';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_EN1" IS '英語フォーマット1';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_EN2" IS '英語フォーマット2';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_EN3" IS '英語フォーマット3';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_EN4" IS '英語フォーマット4';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."FORMAT_SEQ_NO_EN5" IS '英語フォーマット5';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."MAIL_FLG5" IS 'メール連絡(承認連絡)';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."GYOMU_DESC_OVERWRITE_KBN" IS '業務説明上書き区分';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."SUBMIT_WITHDRAW_KBN" IS '提出取下げ区分';
   COMMENT ON COLUMN "M_GYOMU_IRAI"."ATTACH_REQUIRED_KBN" IS '回答添付必須区分';
   COMMENT ON TABLE "M_GYOMU_IRAI"  IS '(業務)依頼マスタ';


   --------------------------------------------------------
   --  DDL for Table M_GYOMU_IRAI_USER used to track users making requests
   --------------------------------------------------------

     CREATE TABLE "M_GYOMU_IRAI_USER"
      (	"CRT_TIMESTAMP" DATE,
   	"CRT_USERID" VARCHAR2(20 BYTE),
   	"UPD_TIMESTAMP" DATE,
   	"UPD_USERID" VARCHAR2(20 BYTE),
   	"SEQ_GYOMU_IRAI_USER" NUMBER(28,0),
   	"SEQ_GYOMU_IRAI" NUMBER(28,0),
   	"USER_KBN" VARCHAR2(1 BYTE),
   	"USERID" VARCHAR2(20 BYTE),
   	"ORG" VARCHAR2(15 BYTE)
      ) SEGMENT CREATION IMMEDIATE
     PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
     STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
     PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
     BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
     TABLESPACE "USERS" ;

      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."CRT_TIMESTAMP" IS '作成日時';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."CRT_USERID" IS '作成者';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."UPD_TIMESTAMP" IS '更新日時';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."UPD_USERID" IS '更新者';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."SEQ_GYOMU_IRAI_USER" IS 'シーケンス';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."SEQ_GYOMU_IRAI" IS '(業務)依頼シーケンス';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."USER_KBN" IS 'ユーザ区分';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."USERID" IS 'ユーザID';
      COMMENT ON COLUMN "M_GYOMU_IRAI_USER"."ORG" IS '所属組織';
      COMMENT ON TABLE "M_GYOMU_IRAI_USER"  IS '(業務)依頼者マスタ';

      --------------------------------------------------------
      --  DDL for Table M_GYOMU_KAITO associated with response or answer
      --------------------------------------------------------

        CREATE TABLE "M_GYOMU_KAITO"
         (	"CRT_TIMESTAMP" DATE,
      	"CRT_USERID" VARCHAR2(20 BYTE),
      	"UPD_TIMESTAMP" DATE,
      	"UPD_USERID" VARCHAR2(20 BYTE),
      	"SEQ_GYOMU_KAITO" NUMBER(28,0),
      	"SEQ_GYOMU_IRAI" NUMBER(28,0),
      	"GROUP_CD" VARCHAR2(20 BYTE),
      	"GROUP_TXT" VARCHAR2(300 BYTE)
         ) SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
       NOCOMPRESS LOGGING
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "USERS" ;

         COMMENT ON COLUMN "M_GYOMU_KAITO"."CRT_TIMESTAMP" IS '作成日時';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."CRT_USERID" IS '作成者';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."UPD_TIMESTAMP" IS '更新日時';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."UPD_USERID" IS '更新者';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."SEQ_GYOMU_KAITO" IS 'シーケンス';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."SEQ_GYOMU_IRAI" IS '(業務)依頼シーケンス';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."GROUP_CD" IS 'グループCD';
         COMMENT ON COLUMN "M_GYOMU_KAITO"."GROUP_TXT" IS 'グループテキスト';
         COMMENT ON TABLE "M_GYOMU_KAITO"  IS '(業務)回答マスタ';
      --------------------------------------------------------
      --  DDL for Table M_GYOMU_KAITO_USER associated with approvers of answers
      --------------------------------------------------------

        CREATE TABLE "M_GYOMU_KAITO_USER"
         (	"CRT_TIMESTAMP" DATE,
      	"CRT_USERID" VARCHAR2(20 BYTE),
      	"UPD_TIMESTAMP" DATE,
      	"UPD_USERID" VARCHAR2(20 BYTE),
      	"SEQ_GYOMU_KAITO_USER" NUMBER(28,0),
      	"SEQ_GYOMU_KAITO" NUMBER(28,0),
      	"USER_KBN" VARCHAR2(1 BYTE),
      	"USERID" VARCHAR2(20 BYTE),
      	"ORG" VARCHAR2(15 BYTE)
         ) SEGMENT CREATION IMMEDIATE
        PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
       NOCOMPRESS LOGGING
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "USERS" ;

         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."CRT_TIMESTAMP" IS '作成日時';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."CRT_USERID" IS '作成者';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."UPD_TIMESTAMP" IS '更新日時';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."UPD_USERID" IS '更新者';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."SEQ_GYOMU_KAITO_USER" IS 'シーケンス';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."SEQ_GYOMU_KAITO" IS '(業務)回答シーケンス';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."USER_KBN" IS 'ユーザ区分';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."USERID" IS 'ユーザID';
         COMMENT ON COLUMN "M_GYOMU_KAITO_USER"."ORG" IS '所属組織';
         COMMENT ON TABLE "M_GYOMU_KAITO_USER"  IS '(業務)回答者マスタ';

         --------------------------------------------------------
         --  DDL for Table T_IRAI store details about various requests
         --------------------------------------------------------

           CREATE TABLE "T_IRAI"
            (	"CRT_TIMESTAMP" DATE,
         	"CRT_USERID" VARCHAR2(20 BYTE),
         	"UPD_TIMESTAMP" DATE,
         	"UPD_USERID" VARCHAR2(20 BYTE),
         	"SEQ_IRAI" NUMBER(28,0),
         	"CYCLE_NO" VARCHAR2(4 BYTE),
         	"GYOMU_CD" VARCHAR2(10 BYTE),
         	"LANG_FLG_JP" VARCHAR2(1 BYTE),
         	"LANG_FLG_EN" VARCHAR2(1 BYTE),
         	"DEFINE_ID1" VARCHAR2(10 BYTE),
         	"DEFINE_ID2" VARCHAR2(10 BYTE),
         	"DEFINE_ID3" VARCHAR2(10 BYTE),
         	"DEFINE_ID4" VARCHAR2(10 BYTE),
         	"DEFINE_ID5" VARCHAR2(10 BYTE),
         	"SHUSHU_YM" VARCHAR2(6 BYTE),
         	"SHUSHU_TXT" VARCHAR2(300 BYTE),
         	"IRAI_YMD" VARCHAR2(8 BYTE),
         	"SHIMEKIRI_YMD" VARCHAR2(8 BYTE),
         	"IRAI_STATUS" VARCHAR2(1 BYTE),
         	"MAIL_FLG1" VARCHAR2(1 BYTE),
         	"MAIL_FLG2" VARCHAR2(1 BYTE),
         	"MAIL_FLG3" VARCHAR2(1 BYTE),
         	"MAIL_FLG4" VARCHAR2(1 BYTE),
         	"IRAISAKI_KBN" VARCHAR2(1 BYTE)
            ) SEGMENT CREATION IMMEDIATE
           PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
          NOCOMPRESS LOGGING
           STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
           PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
           BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
           TABLESPACE "USERS" ;

            COMMENT ON COLUMN "T_IRAI"."CRT_TIMESTAMP" IS '作成日時';
            COMMENT ON COLUMN "T_IRAI"."CRT_USERID" IS '作成者';
            COMMENT ON COLUMN "T_IRAI"."UPD_TIMESTAMP" IS '更新日時';
            COMMENT ON COLUMN "T_IRAI"."UPD_USERID" IS '更新者';
            COMMENT ON COLUMN "T_IRAI"."SEQ_IRAI" IS 'シーケンス';
            COMMENT ON COLUMN "T_IRAI"."CYCLE_NO" IS 'サイクルNo';
            COMMENT ON COLUMN "T_IRAI"."GYOMU_CD" IS '業務CD';
            COMMENT ON COLUMN "T_IRAI"."LANG_FLG_JP" IS '言語フラグ(日)';
            COMMENT ON COLUMN "T_IRAI"."LANG_FLG_EN" IS '言語フラグ(英)';
            COMMENT ON COLUMN "T_IRAI"."DEFINE_ID1" IS '定義ID1';
            COMMENT ON COLUMN "T_IRAI"."DEFINE_ID2" IS '定義ID2';
            COMMENT ON COLUMN "T_IRAI"."DEFINE_ID3" IS '定義ID3';
            COMMENT ON COLUMN "T_IRAI"."DEFINE_ID4" IS '定義ID4';
            COMMENT ON COLUMN "T_IRAI"."DEFINE_ID5" IS '定義ID5';
            COMMENT ON COLUMN "T_IRAI"."SHUSHU_YM" IS '収集年月';
            COMMENT ON COLUMN "T_IRAI"."SHUSHU_TXT" IS '収集テキスト';
            COMMENT ON COLUMN "T_IRAI"."IRAI_YMD" IS '依頼日';
            COMMENT ON COLUMN "T_IRAI"."SHIMEKIRI_YMD" IS '締切日';
            COMMENT ON COLUMN "T_IRAI"."IRAI_STATUS" IS '依頼状態';
            COMMENT ON COLUMN "T_IRAI"."MAIL_FLG1" IS 'メール連絡(マスタ変更)';
            COMMENT ON COLUMN "T_IRAI"."MAIL_FLG2" IS 'メール連絡(承認フロー)';
            COMMENT ON COLUMN "T_IRAI"."MAIL_FLG3" IS 'メール連絡(確認)';
            COMMENT ON COLUMN "T_IRAI"."MAIL_FLG4" IS 'メール連絡(差戻)';
            COMMENT ON TABLE "T_IRAI"  IS '依頼';
         --------------------------------------------------------
         --  DDL for Table T_IRAI_USER stores details about users associated with requests.
         --------------------------------------------------------

           CREATE TABLE "T_IRAI_USER"
            (	"CRT_TIMESTAMP" DATE,
         	"CRT_USERID" VARCHAR2(20 BYTE),
         	"UPD_TIMESTAMP" DATE,
         	"UPD_USERID" VARCHAR2(20 BYTE),
         	"SEQ_IRAI_USER" NUMBER(28,0),
         	"SEQ_IRAI" NUMBER(28,0),
         	"USER_KBN" VARCHAR2(1 BYTE),
         	"USERID" VARCHAR2(20 BYTE),
         	"ORG" VARCHAR2(15 BYTE),
         	"KAISHA" VARCHAR2(300 BYTE),
         	"BUSHO" VARCHAR2(120 BYTE),
         	"YAKUSHOKU" VARCHAR2(90 BYTE),
         	"EMAIL" VARCHAR2(50 BYTE)
            ) SEGMENT CREATION IMMEDIATE
           PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
          NOCOMPRESS LOGGING
           STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
           PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
           BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
           TABLESPACE "USERS" ;

            COMMENT ON COLUMN "T_IRAI_USER"."CRT_TIMESTAMP" IS '作成日時';
            COMMENT ON COLUMN "T_IRAI_USER"."CRT_USERID" IS '作成者';
            COMMENT ON COLUMN "T_IRAI_USER"."UPD_TIMESTAMP" IS '更新日時';
            COMMENT ON COLUMN "T_IRAI_USER"."UPD_USERID" IS '更新者';
            COMMENT ON COLUMN "T_IRAI_USER"."SEQ_IRAI_USER" IS 'シーケンス';
            COMMENT ON COLUMN "T_IRAI_USER"."SEQ_IRAI" IS '依頼シーケンス';
            COMMENT ON COLUMN "T_IRAI_USER"."USER_KBN" IS 'ユーザ区分';
            COMMENT ON COLUMN "T_IRAI_USER"."USERID" IS 'ユーザID';
            COMMENT ON COLUMN "T_IRAI_USER"."ORG" IS '所属組織';
            COMMENT ON COLUMN "T_IRAI_USER"."KAISHA" IS '会社名';
            COMMENT ON COLUMN "T_IRAI_USER"."BUSHO" IS '部署名';
            COMMENT ON COLUMN "T_IRAI_USER"."YAKUSHOKU" IS '役職名';
            COMMENT ON COLUMN "T_IRAI_USER"."EMAIL" IS 'メールアドレス';
            COMMENT ON TABLE "T_IRAI_USER"  IS '依頼者';
         --------------------------------------------------------
         --  DDL for Table T_KAITO stores details about answers associated with a request
         --------------------------------------------------------

           CREATE TABLE "T_KAITO"
            (	"CRT_TIMESTAMP" DATE,
         	"CRT_USERID" VARCHAR2(20 BYTE),
         	"UPD_TIMESTAMP" DATE,
         	"UPD_USERID" VARCHAR2(20 BYTE),
         	"SEQ_KAITO" NUMBER(28,0),
         	"SEQ_IRAI" NUMBER(28,0),
         	"GROUP_CD" VARCHAR2(20 BYTE),
         	"GROUP_TXT" VARCHAR2(300 BYTE),
         	"KAITO_STATUS" VARCHAR2(1 BYTE),
         	"FORMAT_SEQ_NO1" NUMBER(28,0),
         	"FORMAT_SEQ_NO2" NUMBER(28,0),
         	"FORMAT_SEQ_NO3" NUMBER(28,0),
         	"FORMAT_SEQ_NO4" NUMBER(28,0),
         	"FORMAT_SEQ_NO5" NUMBER(28,0),
         	"KAITO_SEQ_NO1" NUMBER(28,0),
         	"KAITO_SEQ_NO2" NUMBER(28,0),
         	"KAITO_SEQ_NO3" NUMBER(28,0),
         	"KAITO_SEQ_NO4" NUMBER(28,0),
         	"KAITO_SEQ_NO5" NUMBER(28,0),
         	"REF_IRAI_SEQ_NO1" NUMBER(28,0),
         	"REF_IRAI_SEQ_NO2" NUMBER(28,0),
         	"REF_IRAI_SEQ_NO3" NUMBER(28,0),
         	"REF_IRAI_SEQ_NO4" NUMBER(28,0),
         	"REF_IRAI_SEQ_NO5" NUMBER(28,0),
         	"REF_KAITO_SEQ_NO1" NUMBER(28,0),
         	"REF_KAITO_SEQ_NO2" NUMBER(28,0),
         	"REF_KAITO_SEQ_NO3" NUMBER(28,0),
         	"REF_KAITO_SEQ_NO4" NUMBER(28,0),
         	"REF_KAITO_SEQ_NO5" NUMBER(28,0),
         	"ORDER_NO" NUMBER(4,0)
            ) SEGMENT CREATION IMMEDIATE
           PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
          NOCOMPRESS LOGGING
           STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
           PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
           BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
           TABLESPACE "USERS" ;

            COMMENT ON COLUMN "T_KAITO"."CRT_TIMESTAMP" IS '作成日時';
            COMMENT ON COLUMN "T_KAITO"."CRT_USERID" IS '作成者';
            COMMENT ON COLUMN "T_KAITO"."UPD_TIMESTAMP" IS '更新日時';
            COMMENT ON COLUMN "T_KAITO"."UPD_USERID" IS '更新者';
            COMMENT ON COLUMN "T_KAITO"."SEQ_KAITO" IS 'シーケンス';
            COMMENT ON COLUMN "T_KAITO"."SEQ_IRAI" IS '依頼シーケンス';
            COMMENT ON COLUMN "T_KAITO"."GROUP_CD" IS 'グループCD';
            COMMENT ON COLUMN "T_KAITO"."GROUP_TXT" IS 'グループテキスト';
            COMMENT ON COLUMN "T_KAITO"."KAITO_STATUS" IS '回答状態';
            COMMENT ON COLUMN "T_KAITO"."FORMAT_SEQ_NO1" IS 'フォーマット1';
            COMMENT ON COLUMN "T_KAITO"."FORMAT_SEQ_NO2" IS 'フォーマット2';
            COMMENT ON COLUMN "T_KAITO"."FORMAT_SEQ_NO3" IS 'フォーマット3';
            COMMENT ON COLUMN "T_KAITO"."FORMAT_SEQ_NO4" IS 'フォーマット4';
            COMMENT ON COLUMN "T_KAITO"."FORMAT_SEQ_NO5" IS 'フォーマット5';
            COMMENT ON COLUMN "T_KAITO"."KAITO_SEQ_NO1" IS '回答1';
            COMMENT ON COLUMN "T_KAITO"."KAITO_SEQ_NO2" IS '回答2';
            COMMENT ON COLUMN "T_KAITO"."KAITO_SEQ_NO3" IS '回答3';
            COMMENT ON COLUMN "T_KAITO"."KAITO_SEQ_NO4" IS '回答4';
            COMMENT ON COLUMN "T_KAITO"."KAITO_SEQ_NO5" IS '回答5';
            COMMENT ON COLUMN "T_KAITO"."REF_IRAI_SEQ_NO1" IS '参考1(依頼元用)';
            COMMENT ON COLUMN "T_KAITO"."REF_IRAI_SEQ_NO2" IS '参考2(依頼元用)';
            COMMENT ON COLUMN "T_KAITO"."REF_IRAI_SEQ_NO3" IS '参考3(依頼元用)';
            COMMENT ON COLUMN "T_KAITO"."REF_IRAI_SEQ_NO4" IS '参考4(依頼元用)';
            COMMENT ON COLUMN "T_KAITO"."REF_IRAI_SEQ_NO5" IS '参考5(依頼元用)';
            COMMENT ON COLUMN "T_KAITO"."REF_KAITO_SEQ_NO1" IS '参考1(依頼先用)';
            COMMENT ON COLUMN "T_KAITO"."REF_KAITO_SEQ_NO2" IS '参考2(依頼先用)';
            COMMENT ON COLUMN "T_KAITO"."REF_KAITO_SEQ_NO3" IS '参考3(依頼先用)';
            COMMENT ON COLUMN "T_KAITO"."REF_KAITO_SEQ_NO4" IS '参考4(依頼先用)';
            COMMENT ON COLUMN "T_KAITO"."REF_KAITO_SEQ_NO5" IS '参考5(依頼先用)';
            COMMENT ON TABLE "T_KAITO"  IS '回答';
         --------------------------------------------------------
         --  DDL for Table T_KAITO_USER stores details associated with user linked to an answer
         --------------------------------------------------------

           CREATE TABLE "T_KAITO_USER"
            (	"CRT_TIMESTAMP" DATE,
         	"CRT_USERID" VARCHAR2(20 BYTE),
         	"UPD_TIMESTAMP" DATE,
         	"UPD_USERID" VARCHAR2(20 BYTE),
         	"SEQ_KAITO_USER" NUMBER(28,0),
         	"SEQ_KAITO" NUMBER(28,0),
         	"USER_KBN" VARCHAR2(1 BYTE),
         	"USERID" VARCHAR2(20 BYTE),
         	"ORG" VARCHAR2(15 BYTE),
         	"KAISHA" VARCHAR2(300 BYTE),
         	"BUSHO" VARCHAR2(120 BYTE),
         	"YAKUSHOKU" VARCHAR2(90 BYTE),
         	"EMAIL" VARCHAR2(50 BYTE)
            ) SEGMENT CREATION IMMEDIATE
           PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
          NOCOMPRESS LOGGING
           STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
           PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
           BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
           TABLESPACE "USERS" ;

            COMMENT ON COLUMN "T_KAITO_USER"."CRT_TIMESTAMP" IS '作成日時';
            COMMENT ON COLUMN "T_KAITO_USER"."CRT_USERID" IS '作成者';
            COMMENT ON COLUMN "T_KAITO_USER"."UPD_TIMESTAMP" IS '更新日時';
            COMMENT ON COLUMN "T_KAITO_USER"."UPD_USERID" IS '更新者';
            COMMENT ON COLUMN "T_KAITO_USER"."SEQ_KAITO_USER" IS 'シーケンス';
            COMMENT ON COLUMN "T_KAITO_USER"."SEQ_KAITO" IS '回答シーケンス';
            COMMENT ON COLUMN "T_KAITO_USER"."USER_KBN" IS 'ユーザ区分';
            COMMENT ON COLUMN "T_KAITO_USER"."USERID" IS 'ユーザID';
            COMMENT ON COLUMN "T_KAITO_USER"."ORG" IS '所属組織';
            COMMENT ON COLUMN "T_KAITO_USER"."KAISHA" IS '会社名';
            COMMENT ON COLUMN "T_KAITO_USER"."BUSHO" IS '部署名';
            COMMENT ON COLUMN "T_KAITO_USER"."YAKUSHOKU" IS '役職名';
            COMMENT ON COLUMN "T_KAITO_USER"."EMAIL" IS 'メールアドレス';
            COMMENT ON TABLE "T_KAITO_USER"  IS '回答者';

            --------------------------------------------------------
            --  DDL for Table T_GUIDE
            --------------------------------------------------------

              CREATE TABLE "T_GUIDE"
               (	"CRT_TIMESTAMP" DATE,
            	"CRT_USERID" VARCHAR2(20 BYTE),
            	"UPD_TIMESTAMP" DATE,
            	"UPD_USERID" VARCHAR2(20 BYTE),
            	"SEQ_GUIDE" NUMBER(28,0),
            	"BEGIN_YMD" DATE,
            	"END_YMD" DATE,
            	"IMPORTANT_FLG" VARCHAR2(1 BYTE),
            	"TITLE" VARCHAR2(100 BYTE),
            	"TEXT" VARCHAR2(4000 BYTE),
            	"ATTACH_CLASS_NO" NUMBER(28,0)
               ) SEGMENT CREATION IMMEDIATE
              PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
             NOCOMPRESS LOGGING
              STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
              PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
              BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
              TABLESPACE "USERS" ;

               COMMENT ON COLUMN "T_GUIDE"."CRT_TIMESTAMP" IS '作成日時';
               COMMENT ON COLUMN "T_GUIDE"."CRT_USERID" IS '作成者';
               COMMENT ON COLUMN "T_GUIDE"."UPD_TIMESTAMP" IS '更新日時';
               COMMENT ON COLUMN "T_GUIDE"."UPD_USERID" IS '更新者';
               COMMENT ON COLUMN "T_GUIDE"."SEQ_GUIDE" IS 'シーケンス';
               COMMENT ON COLUMN "T_GUIDE"."BEGIN_YMD" IS '表示期間(開始)';
               COMMENT ON COLUMN "T_GUIDE"."END_YMD" IS '表示期間(終了)';
               COMMENT ON COLUMN "T_GUIDE"."IMPORTANT_FLG" IS '重要フラグ';
               COMMENT ON COLUMN "T_GUIDE"."TITLE" IS 'タイトル';
               COMMENT ON COLUMN "T_GUIDE"."TEXT" IS '本文';
               COMMENT ON COLUMN "T_GUIDE"."ATTACH_CLASS_NO" IS '添付クラスNo';
               COMMENT ON TABLE "T_GUIDE"  IS 'ガイド';

               -- notice table

                CREATE TABLE "BASE_INFO"
                  (	"CRT_TIMESTAMP" TIMESTAMP (6),
               	"CRT_USERID" VARCHAR2(20 BYTE),
               	"UPD_TIMESTAMP" TIMESTAMP (6),
               	"UPD_USERID" VARCHAR2(20 BYTE),
               	"SEQ_INFO" NUMBER(28,0),
               	"BEGIN_YMD" DATE,
               	"END_YMD" DATE,
               	"IMPORTANT_FLG" VARCHAR2(1 BYTE),
               	"TITLE" VARCHAR2(100 BYTE),
               	"TEXT" VARCHAR2(4000 BYTE),
               	"ATTACH_CLASS_NO" NUMBER(28,0)
                  ) SEGMENT CREATION IMMEDIATE
                 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
                NOCOMPRESS LOGGING
                 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                 TABLESPACE "USERS" ;

                  COMMENT ON COLUMN "BASE_INFO"."CRT_TIMESTAMP" IS '作成日時';
                  COMMENT ON COLUMN "BASE_INFO"."CRT_USERID" IS '作成者ID';
                  COMMENT ON COLUMN "BASE_INFO"."UPD_TIMESTAMP" IS '更新日時';
                  COMMENT ON COLUMN "BASE_INFO"."UPD_USERID" IS '更新者ID';
                  COMMENT ON COLUMN "BASE_INFO"."SEQ_INFO" IS 'シーケンス';
                  COMMENT ON COLUMN "BASE_INFO"."BEGIN_YMD" IS '表示期間（開始）';
                  COMMENT ON COLUMN "BASE_INFO"."END_YMD" IS '表示間（終了）';
                  COMMENT ON COLUMN "BASE_INFO"."IMPORTANT_FLG" IS '重要フラグ　1:重要 0:重要ではない';
                  COMMENT ON COLUMN "BASE_INFO"."TITLE" IS 'タイトル';
                  COMMENT ON COLUMN "BASE_INFO"."TEXT" IS 'テキスト';
                  COMMENT ON COLUMN "BASE_INFO"."ATTACH_CLASS_NO" IS '添付クラスNo';
                  COMMENT ON TABLE "BASE_INFO"  IS 'お知らせ詳細テーブル';
               --------------------------------------------------------
               --  DDL for Table BASE_INFO_VIEW_ROLE - contains subject of publication of base ofinfo tabke
               --------------------------------------------------------

                 CREATE TABLE "BASE_INFO_VIEW_ROLE"
                  (	"SEQ_INFO" NUMBER(28,0),
               	"ROLE" VARCHAR2(20 BYTE)
                  ) SEGMENT CREATION IMMEDIATE
                 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
                NOCOMPRESS LOGGING
                 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                 TABLESPACE "USERS" ;

                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE"."SEQ_INFO" IS 'お知らせテーブルシーケンス';
                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE"."ROLE" IS 'ロール';
                  COMMENT ON TABLE "BASE_INFO_VIEW_ROLE"  IS 'お知らせ公開対象設定テーブル';
               --------------------------------------------------------
               --  DDL for Table BASE_INFO_VIEW_ROLE_NAME table contiaing foreign keys of role and role name
               --------------------------------------------------------

                 CREATE TABLE "BASE_INFO_VIEW_ROLE_NAME"
                  (	"ROLE" VARCHAR2(20 BYTE),
               	"ROLE_NAME" VARCHAR2(300 BYTE),
               	"DESCRIPTION" VARCHAR2(4000 BYTE),
               	"CRT_TIMESTAMP" TIMESTAMP (6),
               	"UPD_TIMESTAMP" TIMESTAMP (6)
                  ) SEGMENT CREATION IMMEDIATE
                 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
                NOCOMPRESS LOGGING
                 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                 TABLESPACE "USERS" ;

                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE_NAME"."ROLE" IS 'ロール';
                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE_NAME"."ROLE_NAME" IS 'ロール名';
                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE_NAME"."DESCRIPTION" IS 'ロール説明';
                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE_NAME"."CRT_TIMESTAMP" IS '作成日時';
                  COMMENT ON COLUMN "BASE_INFO_VIEW_ROLE_NAME"."UPD_TIMESTAMP" IS '更新日時';
                  COMMENT ON TABLE "BASE_INFO_VIEW_ROLE_NAME"  IS 'お知らせ公開対象名テーブル';

                  --------------------------------------------------------
                  --  DDL for Table BASE_ATTACHMENT used to store various proof
                  --------------------------------------------------------

                    CREATE TABLE "BASE_ATTACHMENT"
                     (	"ATTACH_CLASS_NO" NUMBER,
                  	"ATTACHMENT_SEQ_NO" NUMBER,
                  	"FILE_NAME" VARCHAR2(1000 BYTE),
                  	"FILE_SIZE" NUMBER,
                  	"FILE_OBJECT" BLOB,
                  	"UPD_TIMESTAMP" TIMESTAMP (6),
                  	"UPD_USERID" VARCHAR2(20 BYTE),
                  	"CRT_TIMESTAMP" TIMESTAMP (6),
                  	"CRT_USERID" VARCHAR2(20 BYTE),
                  	"SUB_SYSTEM_NAME" VARCHAR2(50 BYTE),
                  	"DELETE_FLG" VARCHAR2(1 BYTE)
                     ) SEGMENT CREATION IMMEDIATE
                    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
                   NOCOMPRESS LOGGING
                    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                    TABLESPACE "USERS"
                   LOB ("FILE_OBJECT") STORE AS SECUREFILE (
                    TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
                    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
                    STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                    PCTINCREASE 0
                    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

                     COMMENT ON COLUMN "BASE_ATTACHMENT"."ATTACH_CLASS_NO" IS '親シーケンス(Ver.3.0.1より追加)';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."ATTACHMENT_SEQ_NO" IS '子シーケンス';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."FILE_NAME" IS 'ファイル名';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."FILE_SIZE" IS 'ファイルサイズ';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."FILE_OBJECT" IS 'オブジェクト(実際のファイル)';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."UPD_TIMESTAMP" IS '更新日時';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."UPD_USERID" IS '更新者';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."CRT_TIMESTAMP" IS '作成日時';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."CRT_USERID" IS '作成者ID';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."SUB_SYSTEM_NAME" IS 'サブシステム名';
                     COMMENT ON COLUMN "BASE_ATTACHMENT"."DELETE_FLG" IS '削除フラグ/1:削除/0:通常（Ver.3.0.1より追加）';
                     COMMENT ON TABLE "BASE_ATTACHMENT"  IS '添付情報テーブル';
                  --------------------------------------------------------
                  --  DDL for Table BASE_ATTACHMENT_AGGREGATED logs table of base_attachment
                  --------------------------------------------------------

                    CREATE TABLE "BASE_ATTACHMENT_AGGREGATED"
                     (	"ATTACH_CLASS_NO" NUMBER,
                  	"ATTACHMENT_SEQ_NO" NUMBER,
                  	"UPD_TIMESTAMP" TIMESTAMP (6),
                  	"UPD_USERID" VARCHAR2(20 BYTE),
                  	"CRT_TIMESTAMP" TIMESTAMP (6),
                  	"CRT_USERID" VARCHAR2(20 BYTE),
                  	"SUB_SYSTEM_NAME" VARCHAR2(50 BYTE),
                  	"DELETE_FLG" VARCHAR2(1 BYTE)
                     ) SEGMENT CREATION IMMEDIATE
                    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
                   NOCOMPRESS LOGGING
                    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                    TABLESPACE "USERS" ;

                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."ATTACH_CLASS_NO" IS '親シーケンス';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."ATTACHMENT_SEQ_NO" IS '子シーケンス(Ver.3.0.1以降では基本的に使用しない)';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."UPD_TIMESTAMP" IS '更新日時';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."UPD_USERID" IS '更新者ID';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."CRT_TIMESTAMP" IS '作成日時';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."CRT_USERID" IS '作成者ID';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."SUB_SYSTEM_NAME" IS 'サブシステム名';
                     COMMENT ON COLUMN "BASE_ATTACHMENT_AGGREGATED"."DELETE_FLG" IS '削除フラグ/1:削除/0:通常（Ver.3.0.1より追加）';
                     COMMENT ON TABLE "BASE_ATTACHMENT_AGGREGATED"  IS '添付ファイル集約テーブル';

