--------------------------------------------------------
--  Constraints for Table M_GYOMU_IRAI
--------------------------------------------------------

  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("SEQ_GYOMU_IRAI" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("GYOMU_CD" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("LANG_FLG_JP" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("LANG_FLG_EN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("EDIT_AUTH_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("IRAISAKI_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("FILE_IMPORT_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("REFERENCE_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" MODIFY ("ACCESS_CTL_KBN" NOT NULL ENABLE);
  ALTER TABLE "M_GYOMU_IRAI" ADD CONSTRAINT "PK_GYOMU_IRAI" PRIMARY KEY ("SEQ_GYOMU_IRAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

  --------------------------------------------------------
  --  Constraints for Table M_GYOMU_IRAI_USER
  --------------------------------------------------------

    ALTER TABLE "M_GYOMU_IRAI_USER" MODIFY ("SEQ_GYOMU_IRAI_USER" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_IRAI_USER" MODIFY ("SEQ_GYOMU_IRAI" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_IRAI_USER" MODIFY ("USER_KBN" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_IRAI_USER" MODIFY ("USERID" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_IRAI_USER" MODIFY ("ORG" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_IRAI_USER" ADD CONSTRAINT "PK_GYOMU_IRAI_USER" PRIMARY KEY ("SEQ_GYOMU_IRAI_USER")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;
  --------------------------------------------------------
  --  Constraints for Table M_GYOMU_KAITO
  --------------------------------------------------------

    ALTER TABLE "M_GYOMU_KAITO" MODIFY ("SEQ_GYOMU_KAITO" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO" MODIFY ("SEQ_GYOMU_IRAI" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO" ADD CONSTRAINT "PK_GYOMU_KAITO" PRIMARY KEY ("SEQ_GYOMU_KAITO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;
  --------------------------------------------------------
  --  Constraints for Table M_GYOMU_KAITO_USER
  --------------------------------------------------------

    ALTER TABLE "M_GYOMU_KAITO_USER" MODIFY ("SEQ_GYOMU_KAITO_USER" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO_USER" MODIFY ("SEQ_GYOMU_KAITO" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO_USER" MODIFY ("USER_KBN" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO_USER" MODIFY ("USERID" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO_USER" MODIFY ("ORG" NOT NULL ENABLE);
    ALTER TABLE "M_GYOMU_KAITO_USER" ADD CONSTRAINT "PK_GYOMU_KAITO_USER" PRIMARY KEY ("SEQ_GYOMU_KAITO_USER")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;

    --------------------------------------------------------
    --  Constraints for Table T_IRAI
    --------------------------------------------------------

      ALTER TABLE "T_IRAI" MODIFY ("SEQ_IRAI" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("CYCLE_NO" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("GYOMU_CD" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("LANG_FLG_JP" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("LANG_FLG_EN" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("IRAI_STATUS" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" MODIFY ("IRAISAKI_KBN" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI" ADD CONSTRAINT "PK_IRAI" PRIMARY KEY ("SEQ_IRAI")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "USERS"  ENABLE;
    --------------------------------------------------------
    --  Constraints for Table T_IRAI_USER
    --------------------------------------------------------

      ALTER TABLE "T_IRAI_USER" MODIFY ("SEQ_IRAI_USER" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI_USER" MODIFY ("SEQ_IRAI" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI_USER" MODIFY ("USER_KBN" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI_USER" MODIFY ("USERID" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI_USER" MODIFY ("ORG" NOT NULL ENABLE);
      ALTER TABLE "T_IRAI_USER" ADD CONSTRAINT "PK_IRAI_USER" PRIMARY KEY ("SEQ_IRAI_USER")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "USERS"  ENABLE;
    --------------------------------------------------------
    --  Constraints for Table T_KAITO
    --------------------------------------------------------

      ALTER TABLE "T_KAITO" MODIFY ("SEQ_KAITO" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO" MODIFY ("SEQ_IRAI" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO" MODIFY ("KAITO_STATUS" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO" ADD CONSTRAINT "PK_KAITO" PRIMARY KEY ("SEQ_KAITO")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "USERS"  ENABLE;
    --------------------------------------------------------
    --  Constraints for Table T_KAITO_USER
    --------------------------------------------------------

      ALTER TABLE "T_KAITO_USER" MODIFY ("SEQ_KAITO_USER" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO_USER" MODIFY ("SEQ_KAITO" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO_USER" MODIFY ("USER_KBN" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO_USER" MODIFY ("USERID" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO_USER" MODIFY ("ORG" NOT NULL ENABLE);
      ALTER TABLE "T_KAITO_USER" ADD CONSTRAINT "PK_KAITO_USER" PRIMARY KEY ("SEQ_KAITO_USER")
      USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
      STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
      PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
      TABLESPACE "USERS"  ENABLE;

      ALTER TABLE "M_GYOMU_IRAI_USER" ADD CONSTRAINT "FK_GYOMU_IRAI_USER" FOREIGN KEY ("SEQ_GYOMU_IRAI")
      	  REFERENCES "M_GYOMU_IRAI" ("SEQ_GYOMU_IRAI") ON DELETE CASCADE ENABLE;
      --------------------------------------------------------
      --  Ref Constraints for Table M_GYOMU_KAITO_USER
      --------------------------------------------------------

        ALTER TABLE "M_GYOMU_KAITO_USER" ADD CONSTRAINT "FK_GYOMU_KAITO_USER" FOREIGN KEY ("SEQ_GYOMU_KAITO")
      	  REFERENCES "M_GYOMU_KAITO" ("SEQ_GYOMU_KAITO") ON DELETE CASCADE ENABLE;

      	  --------------------------------------------------------
          --  Ref Constraints for Table T_KAITO
          --------------------------------------------------------

            ALTER TABLE "T_KAITO" ADD CONSTRAINT "FK_KAITO" FOREIGN KEY ("SEQ_IRAI")
          	  REFERENCES "T_IRAI" ("SEQ_IRAI") ON DELETE CASCADE ENABLE;

          	  --------------------------------------------------------
              --  Constraints for Table T_GUIDE
              --------------------------------------------------------

                ALTER TABLE "T_GUIDE" MODIFY ("SEQ_GUIDE" NOT NULL ENABLE);
                ALTER TABLE "T_GUIDE" MODIFY ("BEGIN_YMD" NOT NULL ENABLE);
                ALTER TABLE "T_GUIDE" MODIFY ("TITLE" NOT NULL ENABLE);
                ALTER TABLE "T_GUIDE" ADD CONSTRAINT "PK_GUIDE" PRIMARY KEY ("SEQ_GUIDE")
                USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
                STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
                PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
                BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
                TABLESPACE "USERS"  ENABLE;

  --------------------------------------------------------
  --  Constraints for Table BASE_INFO
  --------------------------------------------------------

    ALTER TABLE "BASE_INFO" MODIFY ("SEQ_INFO" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO" MODIFY ("BEGIN_YMD" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO" MODIFY ("TITLE" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO" ADD CONSTRAINT "PK_INFO" PRIMARY KEY ("SEQ_INFO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;
  --------------------------------------------------------
  --  Constraints for Table BASE_INFO_VIEW_ROLE
  --------------------------------------------------------

    ALTER TABLE "BASE_INFO_VIEW_ROLE" MODIFY ("SEQ_INFO" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO_VIEW_ROLE" MODIFY ("ROLE" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO_VIEW_ROLE" ADD CONSTRAINT "PK_INFO_VIEW_ROLE" PRIMARY KEY ("SEQ_INFO", "ROLE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;
  --------------------------------------------------------
  --  Constraints for Table BASE_INFO_VIEW_ROLE_NAME
  --------------------------------------------------------

    ALTER TABLE "BASE_INFO_VIEW_ROLE_NAME" MODIFY ("ROLE" NOT NULL ENABLE);
    ALTER TABLE "BASE_INFO_VIEW_ROLE_NAME" ADD CONSTRAINT "PK_INFO_VIEW_ROLE_NAME" PRIMARY KEY ("ROLE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;

    --------------------------------------------------------
    --  Ref Constraints for Table BASE_INFO_VIEW_ROLE
    --------------------------------------------------------

      ALTER TABLE "BASE_INFO_VIEW_ROLE" ADD FOREIGN KEY ("SEQ_INFO")
    	  REFERENCES "BASE_INFO" ("SEQ_INFO") ON DELETE CASCADE ENABLE;
      ALTER TABLE "BASE_INFO_VIEW_ROLE" ADD FOREIGN KEY ("ROLE")
    	  REFERENCES "BASE_INFO_VIEW_ROLE_NAME" ("ROLE") ON DELETE CASCADE ENABLE;

  --------------------------------------------------------
  --  Constraints for Table BASE_ATTACHMENT
  --------------------------------------------------------

    ALTER TABLE "BASE_ATTACHMENT" MODIFY ("ATTACHMENT_SEQ_NO" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT" MODIFY ("FILE_NAME" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT" MODIFY ("FILE_OBJECT" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT" MODIFY ("DELETE_FLG" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT" ADD CONSTRAINT "PK_BASE_ATTACHMENT" PRIMARY KEY ("ATTACHMENT_SEQ_NO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;
  --------------------------------------------------------
  --  Constraints for Table BASE_ATTACHMENT_AGGREGATED
  --------------------------------------------------------

    ALTER TABLE "BASE_ATTACHMENT_AGGREGATED" MODIFY ("ATTACH_CLASS_NO" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT_AGGREGATED" MODIFY ("DELETE_FLG" NOT NULL ENABLE);
    ALTER TABLE "BASE_ATTACHMENT_AGGREGATED" ADD CONSTRAINT "PK_BASE_CLASSED_ATTACHMENT" PRIMARY KEY ("ATTACH_CLASS_NO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE;

