INSERT INTO M_GYOMU_IRAI (
    CRT_TIMESTAMP, CRT_USERID, UPD_TIMESTAMP, UPD_USERID, SEQ_GYOMU_IRAI, GYOMU_CD, LANG_FLG_JP, LANG_FLG_EN,
    GYOMU_NM_JP, GYOMU_NM_EN, DESCRIPTION_JP, DESCRIPTION_EN, SORT, DEFINE_ID1, DEFINE_ID2, DEFINE_ID3,
    DEFINE_ID4, DEFINE_ID5, MAIL_FLG1, MAIL_FLG2, MAIL_FLG3, MAIL_FLG4, ATTACH_CLASS_NO_JP, ATTACH_CLASS_NO_EN,
    EDIT_AUTH_KBN, IRAISAKI_KBN, FILE_IMPORT_KBN, FORMAT_SEQ_NO_JP1, FORMAT_SEQ_NO_JP2, FORMAT_SEQ_NO_JP3,
    FORMAT_SEQ_NO_JP4, FORMAT_SEQ_NO_JP5, FORMAT_SEQ_NO_EN1, FORMAT_SEQ_NO_EN2, FORMAT_SEQ_NO_EN3, FORMAT_SEQ_NO_EN4,
    FORMAT_SEQ_NO_EN5, ATTACH_CLASS_NO_RIYOSHA, DESCRIPTION_RIYOSHA, REFERENCE_KBN, ACCESS_CTL_KBN, MAIL_FLG5,
    GYOMU_DESC_OVERWRITE_KBN, SUBMIT_WITHDRAW_KBN, ATTACH_REQUIRED_KBN
) VALUES (
    SYSDATE, 'USER1', SYSDATE, 'USER1', 1, 'GYOMU001', 'Y', 'Y',
    '業務内容JP1', 'Business Description EN1', '説明内容JP1', 'Description Content EN1', 1, 'DEF01', 'DEF02', 'DEF03',
    'DEF04', 'DEF05', 'N', 'N', 'N', 'N', NULL, NULL,
    'A', 'B', 'C', NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, '1', '1', 'N',
    'N', 'N', 'N'
);

INSERT INTO M_GYOMU_IRAI (
    CRT_TIMESTAMP, CRT_USERID, UPD_TIMESTAMP, UPD_USERID, SEQ_GYOMU_IRAI, GYOMU_CD, LANG_FLG_JP, LANG_FLG_EN,
    GYOMU_NM_JP, GYOMU_NM_EN, DESCRIPTION_JP, DESCRIPTION_EN, SORT, DEFINE_ID1, DEFINE_ID2, DEFINE_ID3,
    DEFINE_ID4, DEFINE_ID5, MAIL_FLG1, MAIL_FLG2, MAIL_FLG3, MAIL_FLG4, ATTACH_CLASS_NO_JP, ATTACH_CLASS_NO_EN,
    EDIT_AUTH_KBN, IRAISAKI_KBN, FILE_IMPORT_KBN, FORMAT_SEQ_NO_JP1, FORMAT_SEQ_NO_JP2, FORMAT_SEQ_NO_JP3,
    FORMAT_SEQ_NO_JP4, FORMAT_SEQ_NO_JP5, FORMAT_SEQ_NO_EN1, FORMAT_SEQ_NO_EN2, FORMAT_SEQ_NO_EN3, FORMAT_SEQ_NO_EN4,
    FORMAT_SEQ_NO_EN5, ATTACH_CLASS_NO_RIYOSHA, DESCRIPTION_RIYOSHA, REFERENCE_KBN, ACCESS_CTL_KBN, MAIL_FLG5,
    GYOMU_DESC_OVERWRITE_KBN, SUBMIT_WITHDRAW_KBN, ATTACH_REQUIRED_KBN
) VALUES (
    SYSDATE, 'USER2', SYSDATE, 'USER2', 2, 'GYOMU002', 'Y', 'Y',
    '業務内容JP2', 'Business Description EN2', '説明内容JP2', 'Description Content EN2', 2, 'DEF11', 'DEF12', 'DEF13',
    'DEF14', 'DEF15', 'N', 'N', 'N', 'N', NULL, NULL,
    'A', 'B', 'C', NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, '1', '1', 'N',
    'N', 'N', 'N'
);
