-- Add primary key to BASE_PARTY_ACCOUNT (ACCOUNT_ID)
ALTER TABLE BASE_PARTY_ACCOUNT
ADD CONSTRAINT PK_BASE_PARTY_ACCOUNT PRIMARY KEY (ACCOUNT_ID);

-- Add primary key to BASE_PARTY_ATTRIBUTE (PARTY_ID)
ALTER TABLE BASE_PARTY_ATTRIBUTE
ADD CONSTRAINT PK_BASE_PARTY_ATTRIBUTE PRIMARY KEY (PARTY_ID);

-- Add foreign key to BASE_PARTY_ACCOUNT referencing BASE_PARTY_ATTRIBUTE
ALTER TABLE BASE_PARTY_ACCOUNT
ADD CONSTRAINT FK_BASE_PARTY_ACCOUNT_PARTY_ID FOREIGN KEY (PARTY_ID)
REFERENCES BASE_PARTY_ATTRIBUTE(PARTY_ID);