INSERT INTO BASE_INFO ("CRT_TIMESTAMP", "CRT_USERID", "UPD_TIMESTAMP", "UPD_USERID", "SEQ_INFO", "BEGIN_YMD", "END_YMD", "IMPORTANT_FLG", "TITLE", "TEXT")
VALUES (SYSTIMESTAMP, 'user3', SYSTIMESTAMP, 'user3', 1004, TO_DATE('2024-07-01', 'YYYY-MM-DD'), TO_DATE('2024-12-31', 'YYYY-MM-DD'), 'N', 'Regular Update', 'This is a regular update for all users.');
